### ISSUE TITLE
cmdline_args failing to build when using C99

### ISSUE THREAD

**Issue by nscooling** [ThrowTheSwitch/Ceedling#747]
When adding to `project.yml`
```
:test_runner:
  :cmdline_args: true
```

to a newly created project, the project fails to build when using C99:
```
Test 'test_thing.c'
-------------------
Generating runner for test_thing.c...
Compiling test_thing_runner.c...
build/test/runners/test_thing_runner.c:77:22: error: implicit declaration of function 'UnityParseOptions' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  int parse_status = UnityParseOptions(argc, argv);
                     ^
1 error generated.
```
The test running is generating:
```
/*=======MAIN=====*/
 int main(int argc, char** argv)
{
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
```

However no declaration is being including in the runner source file, and the prototype for `UnityParseOptions` is not part of `Unity.h`

**Comment by lukzeg** [comment]
Hi @nscooling,

Can you share with me your project.yml and if it is this possible project, so I will be able to reproduce the issue, and fix it.
As well, can you tell me, on which commit/branch you are working on?

**Comment by nscooling** [comment]
Hi @lukzeg - Here is a repo that causes the issue:
[github link](https://github.com/nscooling/ceedling_bug_747)

Version detials
```
$ ceedling version
Welcome to Ceedling!
    Ceedling:: 0.31.1
       CMock:: 2.5.4
       Unity:: 2.5.4
  CException:: 1.3.3
```

macOS Ventura 13.2.1 (22D68)

```
$ gcc -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
$ ruby -v
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]
```

**Comment by lukzeg** [comment]
Hi @nscooling ,

My apologies for a silence from my side. Today I tried to reproduce your issue, but to be honest, on my Ubuntu 24.04 I'm not able to reproduce it.

The project which you shared it works perfectly fine for me.

I as well checked example app under Unity submodule:
https://github.com/ThrowTheSwitch/Unity/tree/master/examples/example_1

where I updated makefile, to fit your needs:
https://github.com/ThrowTheSwitch/Unity/blob/master/examples/example_1/makefile#L30

by updatting **-std=c89** to  **-std=c99** and adding -DUNITY_USE_COMMAND_LINE_ARGS and everything works perfectly fine.

Can you check wherever your vendor/unity submodule is up to date?

Can you as well try to build with verbose logging option:

```sh
ceedling verbosity[4] logging test:all

```
And confirm wherever the **-DUNITY_USE_COMMAND_LINE_ARGS** is visible in your  compilation process? As the error mostly inform that this flag is missing.

---
I was able build this on my Ubuntu 22.04, where:

- vendor/Unity  -> 5a36b197fb34c0a77ac891c355596cb5c25aaf5b 
- Ceedling -> db98f857cbebe80af55a8756720928c90a248c2b

and I'm using gcc -> gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0.

**Comment by mvandervoord** [comment]
This has been fixed in the release candidate. It just hasn't been made official yet. To manually fix it yourself, add `UNITY_USE_COMMAND_LINE_ARGS` to your `project.yml` defines list. In the future, this will be automatically added when this feature is enabled.

**Comment by LuisAfonso95** [comment]
I added 
`  :common: &common_defines 
    - UNITY_USE_COMMAND_LINE_ARGS`

can confirm that does remove the error. I still have issues where it does not allow me to select a test case but it doesn't fit in this issue.



Thank you

**Comment by mkarlesky** [comment]
We are nearing an official release of 0.32. I can confirm that `:test_runner` ↳ `:cmdline_args` works as expected and works without issue when `-std=c99` is added to test executable compilation.
